# Use an official PostgreSQL image as a parent image
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=hbnb_addis_review
ENV POSTGRES_PASSWORD=addisreview
ENV POSTGRES_DB=hbnb_addis_review_db

# Copy the SQL script to create the database and tables
# COPY init.sql /docker-entrypoint-initdb.d/

# Expose the PostgreSQL port
EXPOSE 5432

# Start the PostgreSQL server
CMD ["postgres"]
